### ISSUE TITLE
Possible conflict with another repo

### ISSUE THREAD

**Issue by dreamwhite** [vulgo/IORegistryExplorer#1]
Dear Vulgo,
I'm really glad to reach you via GitHub again. I don't know what exactly happened with your account but as I see you resetted it.

I landed here just to inform you that during your absence on GitHub, I reuploaded (after giving the right credits) IORegistryExplorer v.2.1 and v3.0.2 on [my organization repo](https://github.com/utopia-team/IORegistryExplorer).
Please let me know what should I do with the repository and if I need to delete it eventually.

Regards
dreamwhite

**Comment by vulgo** [comment]
Hi. @1alessandro1 asked me to recreate the repo at the old URL, I guess because deleting it broke some links. No need to mention or credit anyone - it's just an abuse of Github's releases page that may be useful to those Google-ing for version 2.1 - maybe © Apple is nice but not really necessary either. Best regards.
